site_name: 星舟Starship
site_url: https://howcam.github.io/
site_author: Starship Dev Team
edit_uri: edit/main/docs/

repo_url: https://github.com/howcam/howcam.github.io/
repo_name: HowCam/howcam.github.io

copyright: Copyright &copy; 2024 <a href='https://github.com/orgs/Starship-Dev-Team/people'> Starship Dev Team </a>

extra:
  social:
  - icon: octicons/mail-24
    link: mailto:hownotfound@gmail.com
  - icon: fontawesome/brands/github
    link: https://github.com/orgs/Starship-Dev-Team/people

nav:
  - 首页: 
    - 首页: index.md
    - 贡献指南: intro/contribute.md
    - 格式手册: intro/format.md
    - 数学符号表: intro/symbol.md
    - 如何使用GitHub: intro/how-to-use-GitHub.md
    - Markdown扫盲: intro/Markdown.md
    - 加入我们: intro/join-us.md
  - 语文:
    - 语文部分简介: Chinese/Chinese-intro.md
    - 语文笔记: Chinese/语文笔记.md
    - 名著专项:
      - 西游记: Chinese/西游记.md
      - 朝花夕拾: Chinese/朝花夕拾.md
      - 水浒传: Chinese/水浒传.md
      - 儒林外史: Chinese/儒林外史.md
      - 骆驼祥子: Chinese/骆驼祥子.md
      - 钢铁是怎样炼成的: Chinese/钢铁是怎样炼成的.md
      - 昆虫记: Chinese/昆虫记.md
    - 作文专项:
      - 分类作文集锦:
        - 成长篇: Chinese/作文范文/成长篇.md
        - 亲情篇: Chinese/作文范文/亲情篇.md
        - 传统文化类: Chinese/作文范文/传统文化类.md
      - 作文集锦:
        - 我的青春里有一缕清香: Chinese/作文范文/我的青春里有一缕清香.md
        - 终于找到答案: Chinese/作文范文/终于找到答案.md
        - ___＿小天地大: Chinese/作文范文/___＿小天地大.md
        - 青春要有一颗滚烫的心: Chinese/作文范文/青春要有一颗滚烫的心.md
        - 那一抹中国红: Chinese/作文范文/那一抹中国红.md
        - 那堂特别的语文课: Chinese/作文范文/那堂特别的语文课.md
        - 《》让我学会＿_: Chinese/作文范文/《》让我学会＿_.md
        - 不止一次，我＿: Chinese/作文范文/不止一次，我＿.md
        - 冬日也是春: Chinese/作文范文/冬日也是春.md
        - 守护＿_: Chinese/作文范文/守护＿_.md
  - 数学:
    - 数学部分简介: math/math-intro.md
    - 2017CMO-4: math/2017CMO-4.md
  - 历史:
    - 历史部分简介: history/history-intro.md
    - 九年级历史资料: history/九年级历史资料.md
  - 政治:
    - 政治部分简介: politics/politics-intro.md
    - 九年级政治资料: politics/九年级政治资料.md
  - 化学:
    - 化学部分简介: chemistry/chemistry-intro.md
    - 化学笔记: chemistry/化学笔记.md
    - 分章节讲稿:
      - 绪言 化学使世界变得更加绚丽多彩: chemistry/U0.md
  - 物理:
    - 物理部分简介: physics/physics-intro.md
    - 分章节讲稿:
      - 第一章 机械运动: physics/第一章-机械运动.md
      - 第二章 声现象: physics/第二章-声现象.md

theme:
  name: material
  language: zh
  favicon: images/favicon.png
  icon:
    logo: material/ufo-outline
  features:
    - content.action.edit
    - content.action.view
    - navigation.tabs
    - navigation.top
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.footer
    - navigation.tracking
    - search.suggest # 搜索建议
    - search.highlight # 搜索高亮
    - toc.follow # 目录跟踪-页面右侧的小目录
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: green
      accent: deep orange
      toggle:
        icon: material/toggle-switch-off-outline
        name: 切换到暗夜模式

    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/toggle-switch
        name: 切换到日间模式

  plugins:
  - git-committers:
      repository: HowCam/howcam.github.io
      branch: main

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://jsd.cdn.zzko.cn/npm/mathjax@3/es5/tex-chtml.js
      