name: Update CNAME on gh-pages

on:
  push:
    branches:
      - gh-pages

jobs:
  update-cname:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: gh-pages  # 确保切换到 gh-pages 分支

      - name: Update CNAME file
        run: |
          echo "starship.howcam.top" > CNAME
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add CNAME
          git commit -m "Update CNAME to starship.howcam.top" || echo "No changes to CNAME file."
          git push origin gh-pages

      - name: Notify Completion
        run: echo "CNAME file updated to starship.howcam.top"
